# Generated by Django 5.0.4 on 2025-03-01 16:18
from datetime import timedelta

from django.db import migrations

from main_app.models import Order

# Task 10
def update_orders(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    for order in orders:
        if order.status == Order.StatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
        if order.status == Order.StatusChoices.COMPLETED:
            order.warranty = '24 months'
        order.save()
        if order.status == Order.StatusChoices.CANCELLED:
            order.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [
        migrations.RunPython(update_orders),
    ]
