# Generated by Django 5.0.4 on 2025-03-01 16:04

from django.db import migrations

# Task 9 - part 1

def set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.price = len(phone.brand) * 120
        phone.save()

def default_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.price = 0
        phone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price, reverse_code=default_price),
    ]

