# Generated by Django 5.0.4 on 2025-03-01 15:43
from django.db import migrations

# Task 7
def set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    people = person_model.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 18:
            person.age_group = 'Child'
        else:
            person.age_group = 'Adult'
        person.save()

def default_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    people = person_model.objects.all()

    for person in people:
        person.age_group = 'No age group'
        person.save()

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=default_age_group),
    ]
